### ISSUE TITLE
Problems for creating a Carrousel from Thumbnail

### ISSUE THREAD

**Issue by giulianou90** [giulianou90/personal-Portfolio#1]
This issue is related to the **index.html** file.
The scope is to press the 'view' button on bottom of the thumbnail picture, which should shoot an event that makes a Carrousel with dif pictures appear on the center of the screen, which should also have the option to turn back by for instance clicking outside the carrousel.

![image](https://github.com/giulianou90/personal-Portfolio/assets/132233852/5f752ef3-9b69-4cfb-9f63-afd8c0c50a01)

**Comment by lukewelden** [comment]
Hey, @giulianou90 👋

Looking into this now! 🔥

**Comment by giulianou90** [comment]
Thank you, works great
